theme-bootstrap-2:
  use: theme

posts:
  sort: ["date", "desc"]
  rss:
    enable: true

widgets:
  comments:
    use: disqus
    short_name: rust-by-example
  analytics:
    use: google
    tracking_id: UA-4944917-11
  google_prettify:
    use: default
    linenums: false
