theme-bootstrap-2:
  use: theme

widgets:
  comments:
    use: disqus
    short_name: rust-by-example
  analytics:
    use: google
    tracking_id: UA-4944917-11

production_url: 'http://rustbyexample.nobacon.it'
